### ISSUE TITLE
ref2.tif not found error

### ISSUE THREAD

**Issue by StuPidMRE** [vccimaging/DiffOptics#2]
excuse me. where can I get the ref2.tif to run the example code. I went into an error like this
```
DiffMetrology is using: cuda:0
Figure(800x600)
Traceback (most recent call last):
  File "misalignment_point.py", line 97, in <module>
    img = imread('./data/20210304/ref2.tif') # for now we use grayscale
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/matplotlib/image.py", line 1560, in imread
    with img_open(fname) as image:
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/20210304/ref2.tif'
```

**Comment by CongliWANG** [comment]
Thanks for spotting this.  Missing data has been uploaded.  Please pull to the latest version.
